// Catálogo de productos Hacendado con precios reales aproximados
// unidad_base: la unidad en la que se mide el producto internamente (g, ml, ud)
// cantidad_por_envase: cuántas unidades_base tiene el envase (ej: 1000g para 1kg)
// precio: precio del envase completo en euros

const productos = [
  // ────────────── FRUTAS Y VERDURAS ──────────────
  {
    nombre: 'Patatas Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.96,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Patatas para freír Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.10,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Cebolla Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.79,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Cebolla dulce Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Tomate triturado Hacendado',
    categoria: 'Conservas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.49,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },
  {
    nombre: 'Ajo en polvo Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.85,
    unidad_venta: '80 g',
    cantidad_por_envase: 80,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimiento rojo Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.20,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Zanahoria Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.69,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Espinacas frescas Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.09,
    unidad_venta: '300 g',
    cantidad_por_envase: 300,
    unidad_base: 'g',
  },
  {
    nombre: 'Limón Hacendado',
    categoria: 'Frutas',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Manzana Hacendado',
    categoria: 'Frutas',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.49,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Calabacín Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.29,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Calabaza Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.59,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Champiñón laminado Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.45,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Ajo fresco Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.79,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Perejil fresco Hacendado',
    categoria: 'Hierbas',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.89,
    unidad_venta: '50 g',
    cantidad_por_envase: 50,
    unidad_base: 'g',
  },
  {
    nombre: 'Col blanca Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.19,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },

  // ────────────── CARNES Y AVES ──────────────
  {
    nombre: 'Pechuga de pollo Hacendado',
    categoria: 'Aves',
    seccion_tienda: 'Carnes y Aves',
    precio: 3.95,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Pechuga de pavo Hacendado',
    categoria: 'Aves',
    seccion_tienda: 'Carnes y Aves',
    precio: 4.15,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Carne picada mixta Hacendado',
    categoria: 'Carnes',
    seccion_tienda: 'Carnes y Aves',
    precio: 3.49,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Muslos de pollo Hacendado',
    categoria: 'Aves',
    seccion_tienda: 'Carnes y Aves',
    precio: 2.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Jamón serrano loncheado Hacendado',
    categoria: 'Embutidos',
    seccion_tienda: 'Carnes y Aves',
    precio: 1.49,
    unidad_venta: '100 g',
    cantidad_por_envase: 100,
    unidad_base: 'g',
  },
  {
    nombre: 'Salchichas frescas Hacendado',
    categoria: 'Carnes',
    seccion_tienda: 'Carnes y Aves',
    precio: 2.29,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },
  {
    nombre: 'Salchichas tipo Bratwurst Hacendado',
    categoria: 'Carnes',
    seccion_tienda: 'Carnes y Aves',
    precio: 2.49,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },

  // ────────────── PESCADOS Y MARISCOS ──────────────
  {
    nombre: 'Atún en aceite de oliva Hacendado',
    categoria: 'Conservas de pescado',
    seccion_tienda: 'Pescados y Mariscos',
    precio: 0.89,
    unidad_venta: '3 x 80 g',
    cantidad_por_envase: 240,
    unidad_base: 'g',
  },
  {
    nombre: 'Atún al natural Hacendado',
    categoria: 'Conservas de pescado',
    seccion_tienda: 'Pescados y Mariscos',
    precio: 0.95,
    unidad_venta: '3 x 80 g',
    cantidad_por_envase: 240,
    unidad_base: 'g',
  },
  {
    nombre: 'Merluza congelada Hacendado',
    categoria: 'Pescado congelado',
    seccion_tienda: 'Congelados',
    precio: 4.99,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },

  // ────────────── LÁCTEOS Y HUEVOS ──────────────
  {
    nombre: 'Huevos Hacendado M',
    categoria: 'Huevos',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.49,
    unidad_venta: '12 ud',
    cantidad_por_envase: 12,
    unidad_base: 'ud',
  },
  {
    nombre: 'Huevos Hacendado L',
    categoria: 'Huevos',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.69,
    unidad_venta: '12 ud',
    cantidad_por_envase: 12,
    unidad_base: 'ud',
  },
  {
    nombre: 'Leche entera Hacendado',
    categoria: 'Leche',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.68,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Leche semidesnatada Hacendado',
    categoria: 'Leche',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.66,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Mantequilla Hacendado',
    categoria: 'Mantequilla',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.19,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Nata para cocinar Hacendado',
    categoria: 'Nata',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.79,
    unidad_venta: '200 ml',
    cantidad_por_envase: 200,
    unidad_base: 'ml',
  },
  {
    nombre: 'Queso rallado Hacendado',
    categoria: 'Queso',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.85,
    unidad_venta: '150 g',
    cantidad_por_envase: 150,
    unidad_base: 'g',
  },
  {
    nombre: 'Queso rallado mezcla Hacendado',
    categoria: 'Queso',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.95,
    unidad_venta: '150 g',
    cantidad_por_envase: 150,
    unidad_base: 'g',
  },
  {
    nombre: 'Mozzarella rallada Hacendado',
    categoria: 'Queso',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.99,
    unidad_venta: '150 g',
    cantidad_por_envase: 150,
    unidad_base: 'g',
  },
  {
    nombre: 'Mozzarella fresca Hacendado',
    categoria: 'Queso',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.79,
    unidad_venta: '200 g',
    cantidad_por_envase: 200,
    unidad_base: 'g',
  },
  {
    nombre: 'Yogur natural Hacendado',
    categoria: 'Yogures',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.75,
    unidad_venta: '4 x 125 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Yogur griego Hacendado',
    categoria: 'Yogures',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.95,
    unidad_venta: '4 x 125 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },

  // ────────────── PANADERÍA ──────────────
  {
    nombre: 'Pan de molde Hacendado',
    categoria: 'Pan',
    seccion_tienda: 'Panadería y Bollería',
    precio: 1.09,
    unidad_venta: '700 g',
    cantidad_por_envase: 700,
    unidad_base: 'g',
  },

  // ────────────── ACEITES Y CONSERVAS ──────────────
  {
    nombre: 'Aceite de oliva virgen extra Hacendado',
    categoria: 'Aceites',
    seccion_tienda: 'Aceites y Conservas',
    precio: 3.99,
    unidad_venta: '750 ml',
    cantidad_por_envase: 750,
    unidad_base: 'ml',
  },
  {
    nombre: 'Aceite de oliva suave Hacendado',
    categoria: 'Aceites',
    seccion_tienda: 'Aceites y Conservas',
    precio: 3.49,
    unidad_venta: '750 ml',
    cantidad_por_envase: 750,
    unidad_base: 'ml',
  },
  {
    nombre: 'Tomate frito Hacendado',
    categoria: 'Salsas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.69,
    unidad_venta: '350 g',
    cantidad_por_envase: 350,
    unidad_base: 'g',
  },
  {
    nombre: 'Tomate frito receta casera Hacendado',
    categoria: 'Salsas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.79,
    unidad_venta: '350 g',
    cantidad_por_envase: 350,
    unidad_base: 'g',
  },
  {
    nombre: 'Mostaza suave Hacendado',
    categoria: 'Salsas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 1.19,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Caldo de pollo Hacendado',
    categoria: 'Caldos',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.99,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Caldo de verduras Hacendado',
    categoria: 'Caldos',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.95,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Garbanzos cocidos Hacendado',
    categoria: 'Legumbres',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.79,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },
  {
    nombre: 'Garbanzos cocidos eco Hacendado',
    categoria: 'Legumbres',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.89,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },

  // ────────────── PASTA, ARROZ Y LEGUMBRES ──────────────
  {
    nombre: 'Arroz redondo Hacendado',
    categoria: 'Arroz',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.89,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Arroz basmati Hacendado',
    categoria: 'Arroz',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 1.19,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Arroz integral Hacendado',
    categoria: 'Arroz',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 1.05,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Espaguetis Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.59,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Espaguetis integrales Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.79,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Láminas de lasaña Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 1.35,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Macarrones Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.59,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Macarrones integrales Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.79,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Lentejas Hacendado',
    categoria: 'Legumbres',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },

  // ────────────── CONDIMENTOS Y ESPECIAS ──────────────
  {
    nombre: 'Sal marina Hacendado',
    categoria: 'Sal',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.39,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Sal fina Hacendado',
    categoria: 'Sal',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.35,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimienta negra molida Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.79,
    unidad_venta: '50 g',
    cantidad_por_envase: 50,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimienta blanca molida Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.85,
    unidad_venta: '50 g',
    cantidad_por_envase: 50,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimentón dulce Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.89,
    unidad_venta: '75 g',
    cantidad_por_envase: 75,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimentón dulce ahumado Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.95,
    unidad_venta: '75 g',
    cantidad_por_envase: 75,
    unidad_base: 'g',
  },
  {
    nombre: 'Orégano Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.59,
    unidad_venta: '15 g',
    cantidad_por_envase: 15,
    unidad_base: 'g',
  },
  {
    nombre: 'Orégano molido Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.62,
    unidad_venta: '15 g',
    cantidad_por_envase: 15,
    unidad_base: 'g',
  },
  {
    nombre: 'Harina de trigo Hacendado',
    categoria: 'Harinas',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.69,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Azúcar blanco Hacendado',
    categoria: 'Azúcar',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.85,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Levadura química Hacendado',
    categoria: 'Repostería',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.79,
    unidad_venta: '6 x 16 g',
    cantidad_por_envase: 96,
    unidad_base: 'g',
  },
  {
    nombre: 'Col lombarda Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.35,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Mostaza antigua Hacendado',
    categoria: 'Salsas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 1.39,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  { nombre: 'Lentejas pardinas Hacendado', categoria: 'Legumbres', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.50, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Chorizo sarta Hacendado', categoria: 'Embutidos', seccion_tienda: 'Carnes y Aves', precio: 2.10, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Ajos Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.20, unidad_venta: 'malla 4 uds', cantidad_por_envase: 4, unidad_base: 'ud' },
  { nombre: 'Lomos de salmón Hacendado', categoria: 'Pescado', seccion_tienda: 'Pescados y Mariscos', precio: 5.95, unidad_venta: '300 g', cantidad_por_envase: 300, unidad_base: 'g' },
  { nombre: 'Tomate ensalada Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.80, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Jamón cocido extra Hacendado', categoria: 'Embutidos', seccion_tienda: 'Carnes y Aves', precio: 2.30, unidad_venta: '200 g', cantidad_por_envase: 200, unidad_base: 'g' },
  { nombre: 'Pollo entero troceado Hacendado', categoria: 'Carne', seccion_tienda: 'Carnes y Aves', precio: 4.50, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Vino blanco Hacendado', categoria: 'Bebidas', seccion_tienda: 'Bebidas', precio: 1.50, unidad_venta: '1 l', cantidad_por_envase: 1000, unidad_base: 'ml' },
  { nombre: 'Aguacates Hacendado', categoria: 'Frutas', seccion_tienda: 'Frutas y Verduras', precio: 2.99, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Espirales Hacendado', categoria: 'Pasta', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 0.85, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Salsa Pesto Hacendado', categoria: 'Salsas', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.95, unidad_venta: '190 g', cantidad_por_envase: 190, unidad_base: 'g' },
  { nombre: 'Pan de molde rústico Hacendado', categoria: 'Panadería', seccion_tienda: 'Panadería y Bollería', precio: 1.40, unidad_venta: '450 g', cantidad_por_envase: 10, unidad_base: 'ud' },
  { nombre: 'Manzana Fuji Hacendado', categoria: 'Frutas', seccion_tienda: 'Frutas y Verduras', precio: 1.99, unidad_venta: '1 kg', cantidad_por_envase: 6, unidad_base: 'ud' },
  { nombre: 'Plátano de Canarias Hacendado', categoria: 'Frutas', seccion_tienda: 'Frutas y Verduras', precio: 2.10, unidad_venta: '1 kg', cantidad_por_envase: 6, unidad_base: 'ud' },
  { nombre: 'Naranja Hacendado', categoria: 'Frutas', seccion_tienda: 'Frutas y Verduras', precio: 1.50, unidad_venta: '1 kg', cantidad_por_envase: 5, unidad_base: 'ud' }
,
  { nombre: 'Mascarpone Hacendado', categoria: 'Lácteos', seccion_tienda: 'Lácteos y Huevos', precio: 2.30, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Salsa Teriyaki Hacendado', categoria: 'Salsas', seccion_tienda: 'Condimentos y Especias', precio: 1.80, unidad_venta: '250 ml', cantidad_por_envase: 250, unidad_base: 'ml' },
  { nombre: 'Tortillas de maíz Hacendado', categoria: 'Panadería', seccion_tienda: 'Panadería y Bollería', precio: 1.50, unidad_venta: '10 uds', cantidad_por_envase: 10, unidad_base: 'ud' },
  { nombre: 'Nata líquida para postres Hacendado', categoria: 'Lácteos', seccion_tienda: 'Lácteos y Huevos', precio: 1.20, unidad_venta: '500 ml', cantidad_por_envase: 500, unidad_base: 'ml' },
  { nombre: 'Algas Nori Hacendado', categoria: 'Internacional', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 2.10, unidad_venta: '5 uds', cantidad_por_envase: 5, unidad_base: 'ud' },
  { nombre: 'Arroz para sushi Hacendado', categoria: 'Arroz', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.60, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Queso Parmesano Hacendado', categoria: 'Lácteos', seccion_tienda: 'Lácteos y Huevos', precio: 3.50, unidad_venta: '200 g', cantidad_por_envase: 200, unidad_base: 'g' },
  { nombre: 'Salsa César Hacendado', categoria: 'Salsas', seccion_tienda: 'Condimentos y Especias', precio: 1.40, unidad_venta: '250 ml', cantidad_por_envase: 250, unidad_base: 'ml' },
  { nombre: 'Mantequilla sin sal Hacendado', categoria: 'Lácteos', seccion_tienda: 'Lácteos y Huevos', precio: 2.00, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Chocolate fondant postres Hacendado', categoria: 'Dulces', seccion_tienda: 'Otros', precio: 1.25, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Nueces peladas Hacendado', categoria: 'Frutos Secos', seccion_tienda: 'Otros', precio: 3.20, unidad_venta: '200 g', cantidad_por_envase: 200, unidad_base: 'g' },
  { nombre: 'Leche de coco Hacendado', categoria: 'Internacional', seccion_tienda: 'Bebidas', precio: 1.45, unidad_venta: '400 ml', cantidad_por_envase: 400, unidad_base: 'ml' },
  { nombre: 'Salsa Tikka Masala Hacendado', categoria: 'Internacional', seccion_tienda: 'Condimentos y Especias', precio: 2.00, unidad_venta: '300 g', cantidad_por_envase: 300, unidad_base: 'g' },
  { nombre: 'Yogur griego natural Hacendado', categoria: 'Lácteos', seccion_tienda: 'Lácteos y Huevos', precio: 1.60, unidad_venta: '6 uds', cantidad_por_envase: 6, unidad_base: 'ud' },
  { nombre: 'Cilantro fresco Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.00, unidad_venta: '1 ud', cantidad_por_envase: 1, unidad_base: 'ud' },
  { nombre: 'Maicena Hacendado', categoria: 'Despensa', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.10, unidad_venta: '400 g', cantidad_por_envase: 400, unidad_base: 'g' },
  { nombre: 'Azúcar blanco Hacendado', categoria: 'Despensa', seccion_tienda: 'Otros', precio: 1.35, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Cuscús Hacendado', categoria: 'Despensa', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.15, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Limón Hacendado', categoria: 'Frutas', seccion_tienda: 'Frutas y Verduras', precio: 1.80, unidad_venta: '1 kg', cantidad_por_envase: 6, unidad_base: 'ud' },
  { nombre: 'Aceitunas verdes deshuesadas Hacendado', categoria: 'Aperitivos', seccion_tienda: 'Aceites y Conservas', precio: 1.40, unidad_venta: '3 uds', cantidad_por_envase: 3, unidad_base: 'ud' },
  { nombre: 'Placas de lasaña Hacendado', categoria: 'Pasta', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.50, unidad_venta: '20 uds', cantidad_por_envase: 20, unidad_base: 'ud' },
  { nombre: 'Bizcochos de soletilla Hacendado', categoria: 'Dulces', seccion_tienda: 'Panadería y Bollería', precio: 1.45, unidad_venta: '400 g', cantidad_por_envase: 400, unidad_base: 'g' },
  { nombre: 'Cacao puro en polvo Hacendado', categoria: 'Despensa', seccion_tienda: 'Otros', precio: 2.60, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Arroz redondo Hacendado', categoria: 'Arroz', seccion_tienda: 'Pasta, Arroz y Legumbres', precio: 1.20, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Gambón crudo Hacendado', categoria: 'Pescado', seccion_tienda: 'Congelados', precio: 8.50, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Mejillón de Chile Hacendado', categoria: 'Pescado', seccion_tienda: 'Congelados', precio: 3.50, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Guisantes finos Hacendado', categoria: 'Verduras', seccion_tienda: 'Congelados', precio: 1.30, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Pimiento verde Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.99, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Pepino Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.20, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Picatostes Hacendado', categoria: 'Panadería', seccion_tienda: 'Panadería y Bollería', precio: 1.00, unidad_venta: '100 g', cantidad_por_envase: 100, unidad_base: 'g' },
  { nombre: 'Sazonador para Fajitas Hacendado', categoria: 'Condimentos', seccion_tienda: 'Condimentos y Especias', precio: 1.25, unidad_venta: '30 g', cantidad_por_envase: 30, unidad_base: 'g' },
  { nombre: 'Piña en su jugo Hacendado', categoria: 'Conservas', seccion_tienda: 'Aceites y Conservas', precio: 1.80, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Tortillas chips nachos Hacendado', categoria: 'Aperitivos', seccion_tienda: 'Otros', precio: 1.10, unidad_venta: '150 g', cantidad_por_envase: 150, unidad_base: 'g' },
  { nombre: 'Vinagre de arroz Hacendado', categoria: 'Salsas', seccion_tienda: 'Condimentos y Especias', precio: 1.50, unidad_venta: '250 ml', cantidad_por_envase: 250, unidad_base: 'ml' },
  { nombre: 'Sésamo tostado Hacendado', categoria: 'Especias', seccion_tienda: 'Condimentos y Especias', precio: 1.35, unidad_venta: '50 g', cantidad_por_envase: 50, unidad_base: 'g' },
  { nombre: 'Brócoli Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.50, unidad_venta: '500 g', cantidad_por_envase: 500, unidad_base: 'g' },
  { nombre: 'Pan de pita Hacendado', categoria: 'Panadería', seccion_tienda: 'Panadería y Bollería', precio: 1.40, unidad_venta: '6 uds', cantidad_por_envase: 6, unidad_base: 'ud' },
  { nombre: 'Huevos Hacendado M', categoria: 'Huevos', seccion_tienda: 'Lácteos y Huevos', precio: 2.20, unidad_venta: '1 docena', cantidad_por_envase: 12, unidad_base: 'ud' },
  { nombre: 'Canela molida Hacendado', categoria: 'Especias', seccion_tienda: 'Condimentos y Especias', precio: 1.00, unidad_venta: '50 g', cantidad_por_envase: 50, unidad_base: 'g' }
,
  { nombre: 'Uvas pasas sultanas Hacendado', categoria: 'Frutos Secos', seccion_tienda: 'Otros', precio: 1.50, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' },
  { nombre: 'Café molido Hacendado', categoria: 'Café', seccion_tienda: 'Bebidas', precio: 2.10, unidad_venta: '250 g', cantidad_por_envase: 250, unidad_base: 'g' }
,
  { nombre: 'Tomate pera Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.85, unidad_venta: '1 kg', cantidad_por_envase: 1000, unidad_base: 'g' },
  { nombre: 'Corazones de lechuga romana Hacendado', categoria: 'Verduras', seccion_tienda: 'Frutas y Verduras', precio: 1.20, unidad_venta: '3 uds', cantidad_por_envase: 3, unidad_base: 'ud' }
];

module.exports = productos;
